version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gallery
    volumes:
      - ./mongo-volume:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongo
    volumes:
      - ./images:/images
